### ISSUE TITLE
Visual mode selection setting is different from default vim setting

### ISSUE THREAD

**Issue by alcazoid** [LightTable/Vim#52] opened 2015-02-04 15:19 UTC
By default vim mode in lighttable doesn't include the character under the cursor, which is different from vim default.

>The highlighted text normally includes the character under the cursor.
>However, when the 'selection' option is set to "exclusive" and the cursor is
after the Visual area, the character under the cursor is not included.

It'd be great to get it fixed or get it as an option.

**Comment by cldwalker** [comment] 2015-02-06 20:50
This is a dupe of #22. Updated its title to be more clear

**Closed by cldwalker** 2015-02-06 20:50 UTC
